image: archlinux:latest

variables:
  PYTHONPATH: "."

before_script:
  - pacman -Syu --noconfirm --noprogressbar --needed
           python-pytest python-pytest-cov ruff make


test:
  script:
    - make lint
    - make test
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
