image: "archlinux:latest"

variables:
  PYTHONPATH: "."

before_script:
  - pacman -Syu --noconfirm --noprogressbar --needed
           python-pytest python-pytest-cov flake8 make


test:
  script:
    - make lint
    - make test
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
